spring:
  datasource:
    origin:
      url: jdbc:mysql://192.168.101.61:3306/bwoil_migration?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: bwoil@20141030
      driver-class-name: com.mysql.cj.jdbc.Driver
    target:
      url: jdbc:mysql://localhost:3306/bwoil_refactor?allowMultiQueries=true&autoReconnect=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
      username: root
      password: '!QAZxsw2'
      driver-class-name: com.mysql.cj.jdbc.Driver
fdfs:
  so-timeout: 6000
  connect-timeout: 6000
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    - 192.168.101.58:22122
  pool:
    max-total: 5000
nfs-path: 'F:'