SELECT * FROM BATCH_STEP_EXECUTION ORDER BY write_count DESC;
SELECT i.JOB_NAME,e.*
FROM BATCH_JOB_EXECUTION e
LEFT JOIN BATCH_JOB_INSTANCE i ON e.JOB_INSTANCE_ID = i.JOB_INSTANCE_ID;

SELECT i.JOB_NAME,s.*
FROM BATCH_STEP_EXECUTION s
LEFT JOIN BATCH_JOB_EXECUTION e ON s.JOB_EXECUTION_ID = e.JOB_EXECUTION_ID
LEFT JOIN BATCH_JOB_INSTANCE i ON e.JOB_INSTANCE_ID = i.JOB_INSTANCE_ID
ORDER BY s.JOB_EXECUTION_ID;

SELECT 
i.JOB_INSTANCE_ID,
e.JOB_EXECUTION_ID, 
i.JOB_NAME,
e.START_TIME,
e.END_TIME,
TIMESTAMPDIFF(SECOND,e.START_TIME,e.END_TIME) AS '执行时间(秒)', TIMESTAMPDIFF(MINUTE,e.START_TIME,e.END_TIME) AS '执行时间(分)', SUM(s.READ_COUNT) AS '读取条数', SUM(s.WRITE_COUNT) AS '写入条数', SUM(s.WRITE_COUNT)/ TIMESTAMPDIFF(SECOND,e.START_TIME,e.END_TIME) AS '每秒写入条数'
FROM BATCH_STEP_EXECUTION s
LEFT JOIN BATCH_JOB_EXECUTION e ON s.JOB_EXECUTION_ID = e.JOB_EXECUTION_ID
LEFT JOIN BATCH_JOB_INSTANCE i ON e.JOB_INSTANCE_ID = i.JOB_INSTANCE_ID
GROUP BY s.JOB_EXECUTION_ID
ORDER BY s.JOB_EXECUTION_ID